# Generated by Django 3.2 on 2021-05-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='jira_response',
            field=models.JSONField(default=None),
        ),
    ]
